### ISSUE TITLE
Im Ziellaufwerk werden die Plots mit der Endung .tmp kopiert. 

### ISSUE THREAD

**Issue by FarmingKid** [mech2you/Chia#1]
Bei den finalen Plots wird beim Kopiervorgang aus der Endung .plot --> .plot.tmp

**Comment by mech2you** [comment]
Aktuell ist Version 1.1.4 raus. Gilt das auch für diese?
Was genau meist du mit finalen Plot?
-> Wenn eine Platte voll ist?
-> Wenn keine Laufwerke mehr da sind da alles vollgeplottet ist?
-> Wenn der Plotter fertig mit den Anzahl der Plots ist? 
.tmp ist meist das der Plot nicht fertig ist. Passiert bei mir wenn z.B. der USB Controller aussteigt weil ich zu viele HDDs an einen System dran hab. Welches Betriebssystem verwendest du und wird auf HDDs oder auf Netzlaufwerke kopiert?

**Comment by FarmingKid** [comment]
ich habe bei mir noch die Version 1.1.3 laufen. 
Betriebssystem Windows 10
Kopiert wurde sowohl auf Netzlaufwerke als auch lokale HDD
Eingestellt ist das so:
-t A:\
-2 P:\

Finaler Plot landet nach Erstellung auf A:\ mit Endung .plot
Nach Kopiervorgang landet der Plot auf einer der Ziellaufwerke mit Endung .plot.tmp

Habe das ganze auch so getestet, dass ich lediglich die Kopierfunktion im Plotmanager gestartet habe in dem dann die Plots von A:\ auf die Ziellaufwerke kopiert wird. 

Frage: die kopierten Plots sollten nach abgeschlossenen Kopiervorgang vom -t gelöscht werden? wenn ja, das hat bei mir ebenfalls beim lediglichen starten der Kopierfunktion nicht funktioniert.

**Comment by mech2you** [comment]
Schick mal bitte ein Screenshot von den Einstellungen in der Software. Hast du versucht das Programm mal diese als Admin laufen zu lassen? Ich vermute das hat was mit Zugriffsrechten zu tun. Manchmal braucht man für das löschen von bestimmten Dateien Admin rechte. Ist halt Windows. Verwendest du den Plotter über die Software oder lässt du ihn separat in der CMD laufen?

**Comment by mech2you** [comment]
@grandee89  Versuche mal die neue Version https://github.com/mech2you/Chia/releases/tag/Version1.1.5 Hab mal einen Button hinzugefügt der prüft ob man auf die Laufwerke lesen, schreiben, umbennen und löschen kann.

**Comment by FarmingKid** [comment]
Entschuldige kam nicht vorher dazu. hier noch ein Screenshot von den Einstellungen 
![image](https://user-images.githubusercontent.com/80603545/225595412-0949a6b6-81c9-4888-8fa5-84c1491eb97f.png)

Hier noch der Test mit der Version 1.1.5 --> Zugriffsrechte sind vorhanden
![image](https://user-images.githubusercontent.com/80603545/225598005-809ca790-1599-466f-a150-93f504d15cb6.png)

Das wird wärend dem Kopiervorgang angezeigt:
![image](https://user-images.githubusercontent.com/80603545/225599357-34adb340-a695-40d6-84d5-3ca3638e640b.png)

Zum Ende kommt folgender Fehler:
Fehler Datei E:\1\plot-k32-c8-2023-03-16-11-56-...546hsh.plot konnte nicht nach \\10.0.0.10\4\plot-k32-c8-2023-03-16-11-56-...546hsh.plot.tmp kopiert werden
System.IO.IOException: IO operation will not work. Most likely the file will become too long.
   at System.IO.RandomAccess.WriteSyncUsingAsyncHandle(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan(ReadOnlySpan`1 source, ArraySegment`1 arraySegment)
   at System.IO.FileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.copyNetwork(String _quelldatei, String _zieldatei) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 81
Fehler Datei konnte nicht umbenannt werdenE:\1\plot-k32-c8-2023-03-16-11-56-f9...546hsh.plot
System.IO.IOException: The process cannot access the file 'E:\1\plot-k32-c8-2023-03-16-11-56-...546hsh.plot' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.BWkopiervorgang_starten(Object sender, DoWorkEventArgs e) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 143

Es scheint als würde der Prozess auch irgendwo stecken bleiben, kann die Datei im Ziellaufwerk auch nicht manuell abändern solange der Plotmanager noch geöffnet ist. Kopiervorgang habe ich bereits angehalten, jedoch kommt weiterhin, dass die Datei zur Zeit noch verwendet wird.

**Comment by mech2you** [comment]
Ich würde es erst schaffen nächste Wochenende das mal zu testen wo das Problem ist. Was du machen könntest ist das Laufwerk nicht über \\IP\Pfad zuzugreifen sondern über den Arbeitsplatz/Mein PC mal einzubinden. 
![image](https://user-images.githubusercontent.com/61209759/225768702-21bb6b6b-de8b-40d1-8f6f-29abfeabc14a.png)
Dann den Pfad über ein Laufwerk verbinden. 
![image](https://user-images.githubusercontent.com/61209759/225768980-0562f727-75c2-433e-b39f-6ba531079fd3.png)
Das sollte nicht die Probleme erzeugen. Wenn du dann über z.B. Z:\\ als Ziellaufwerk wählt. Ist erst mal ein Workaround hoffe ich ;)

**Comment by FarmingKid** [comment]
Kein Problem. Ich versuch einmal dein Workaround.

**Comment by FarmingKid** [comment]
Hab erneut mit der Version 1.1.10 getestet. scheint immernoch nicht richtig zu funktionieren

----
Pfad vorhanden -> E:\\
Erstellen einer Testdatei -> E:\\test.txt
Datei unbenannt von -> E:\\test.txt zu E:\\test1.txt
Inhalt der Datei konnte gelesen werden -> E:\\test1.txt
Datei konnte gelöscht werden -> E:\\test1.txt
Test Erfolgreich für Pfad E:\\
Pfad vorhanden -> D:\\
Erstellen einer Testdatei -> D:\\test.txt
Datei unbenannt von -> D:\\test.txt zu D:\\test1.txt
Inhalt der Datei konnte gelesen werden -> D:\\test1.txt
Datei konnte gelöscht werden -> D:\\test1.txt
Test Erfolgreich für Pfad D:\\
Pfad vorhanden -> R:\\
Erstellen einer Testdatei -> R:\\test.txt
Datei unbenannt von -> R:\\test.txt zu R:\\test1.txt
Inhalt der Datei konnte gelesen werden -> R:\\test1.txt
Datei konnte gelöscht werden -> R:\\test1.txt
Test Erfolgreich für Pfad R:\\
Pfad vorhanden -> Y:\\
Erstellen einer Testdatei -> Y:\\test.txt
Datei unbenannt von -> Y:\\test.txt zu Y:\\test1.txt
Inhalt der Datei konnte gelesen werden -> Y:\\test1.txt
Datei konnte gelöscht werden -> Y:\\test1.txt
Test Erfolgreich für Pfad Y:\\
Pfad vorhanden -> Z:\\
Erstellen einer Testdatei -> Z:\\test.txt
Datei unbenannt von -> Z:\\test.txt zu Z:\\test1.txt
Inhalt der Datei konnte gelesen werden -> Z:\\test1.txt
Datei konnte gelöscht werden -> Z:\\test1.txt
Test Erfolgreich für Pfad Z:\\
Test Erfolgreich für 5 Laufwerk/e
kopieren von E:\\plot-k32-c8-2023-03-23-13-22-...cebf58a9cd.plot nach Z:\\plot-k32-c8-2023-03-23-13-22-...12113a281727a8f35cebf58a9cd.plot.tmp Uhrzeit: 13:58
kopieren von E:\\plot-k32-c8-2023-03-23-13-18-....9a25ac5f077.plot nach Y:\\plot-k32-c8-2023-03-23-13-18-....9a25ac5f077.plot.tmp Uhrzeit: 13:58
kopieren von E:\\plot-k32-c8-2023-03-23-12-34-....968b54474ecf.plot nach R:\\plot-k32-c8-2023-03-23-12-34-....968b54474ecf.plot.tmp Uhrzeit: 13:58
kopieren von E:\\plot-k32-c8-2023-03-23-12-26-...95cd33.plot nach D:\\plot-k32-c8-2023-03-23-12-26-...95cd33.plot.tmp Uhrzeit: 13:58
Fehler Netzwerk Datei E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot konnte nicht nach D:\\plot-k32-c8-2023-03-23-12-26-...df3e95cd33.plot.tmp kopiert werden
System.IO.IOException: IO operation will not work. Most likely the file will become too long.
   at System.IO.RandomAccess.WriteSyncUsingAsyncHandle(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan(ReadOnlySpan`1 source, ArraySegment`1 arraySegment)
   at System.IO.FileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.copyNetwork(String _quelldatei, String _zieldatei) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 95
Fahler Kopieren nach E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot fehlgeschlagen
kopieren von E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot nach D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp Uhrzeit: 14:10
Fehler Alte kopiere Plotdatei konnte nicht gelöscht werden ->D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp
System.IO.IOException: The process cannot access the file 'D:\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.BWkopiervorgang_starten(Object sender, DoWorkEventArgs e) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 147
Fehler Netzwerk Datei E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot konnte nicht nach D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp kopiert werden
System.IO.IOException: The process cannot access the file 'D:\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.copyNetwork(String _quelldatei, String _zieldatei) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 74
Fahler Kopieren nach E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot fehlgeschlagen
kopieren von E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot nach D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp Uhrzeit: 14:10
Fehler Alte kopiere Plotdatei konnte nicht gelöscht werden ->D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp
System.IO.IOException: The process cannot access the file 'D:\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.BWkopiervorgang_starten(Object sender, DoWorkEventArgs e) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 147
Fehler Netzwerk Datei E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot konnte nicht nach D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp kopiert werden
System.IO.IOException: The process cannot access the file 'D:\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Daten_kopieren_Chia_GPU_Plotter.Kopiervorgang.copyNetwork(String _quelldatei, String _zieldatei) in C:\Users\micro\Documents\GitHub\Chia\Daten kopieren Chia GPU Plotter\Daten kopieren Chia GPU Plotter\Kopiervorgang.cs:line 74
Fahler Kopieren nach E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot fehlgeschlagen
kopieren von E:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot nach D:\\plot-k32-c8-2023-03-23-12-26-...ce0df3e95cd33.plot.tmp Uhrzeit: 14:10

---

Funktioniert das Ganze nur wenn Plotter und Kopiervorgang aus einem kommt? ich hatte bis jetzt das Plotting direkt im Terminal gestartet.
